[package]
name = "maincopy-shared"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
schema = ["dep:utoipa", "utoipa/time", "utoipa/uuid"]

[dependencies]
serde.workspace = true
time.workspace = true
utoipa = { workspace = true, optional = true }
uuid = { workspace = true, features = ["serde"] }
zeroize = { workspace = true, features = ["alloc"] }

[dev-dependencies]
serde_json.workspace = true
